### ISSUE TITLE
How use with AJAX requests?

### ISSUE THREAD

**Issue by AienTech** [jagilpe/ajax-blocks-bundle#1]
Hey there,

thanks for this bundle, its really useful. But I've got a question, how can I rerender the block after an AJAX request?

The request is sending the desired data to the controller, and the controller renders the AJAXBlock as response. but nothing happens at that moment.

I expected that the block will be re-rendered after I sent the request to controller. Am I doing something wrong?

**Comment by ghost** [comment]
Hi,
I'm glad you find it useful.

The idea of this bundle is to reload dynamically certain parts of the page without having to worry about the AJAX request. If you want to reload **all** the ajax blocks in your page you have to call in your javascript the following code:
```javascript
$('[data-target="jgp-ajax-block"]').jgpAjaxBlock('reloadBlock');
```
If you only want to reload determined blocks you can use a more specific selector:
```javascript
$('#a-determined-block [data-target="jgp-ajax-block"]').jgpAjaxBlock('reloadBlock');
```
For example, you want to reload the blocks when you click in a button you'd write it in the on click event handler:
```javascript
$('button#reload-blocks').click(function() {
    $('[data-target="jgp-ajax-block"]').jgpAjaxBlock('reloadBlock');
});
```
I have another repo with a demo of this and other Symfony bundles I have written, if you want to see a working example: 
https://github.com/jagilpe/bundles-demo
The javascript code you'd be interested in is in:
https://github.com/jagilpe/bundles-demo/blob/master/app/Resources/views/ajax_blocks_demo/simple.html.twig

**Comment by AienTech** [comment]
Thanks for the answer, I looked at your codes really closely, but it's still not working for me.

the pair of AJAX code that I'm using is
```
$.ajax({
    url     : '{{ (path('product_ajax_request')) }}',
        type    : "GET",
        dataType: "json",
        data    : {
            "item": $(this).data("item"),
            "slug": $(this).data("slug"),
        },
        async   : true,
        success : function (data) {
            $('[data-target="jgp-ajax-block"]').jgpAjaxBlock('reloadBlock');
        },
});
```

and that's what the controller does:
```
    public function productAjaxAction(Request $request)
    {
        $item = $request->get('item');
        $slug = $request->get('slug');

        $em = $this->get('doctrine.orm.entity_manager');
        $locale = $em->getRepository('AppBundle:Language')
            ->findOneBy(
                [
                    'slug' => $this->get('request')->getLocale(),
                ]
            );

        /**
         * @var $productGroup ProductGroup
         */
        $productGroup = $em->getRepository('AppBundle:ProductGroup')
            ->findOneBy(
                [
                    'slug'     => $slug,
                    'language' => $locale,
                ]
            );

        $product = $em->getRepository('AppBundle:Product')
            ->findOneBy(
                [
                    'slug'     => $item,
                    'language' => $locale,
                    'group'    => $productGroup,
                ]
            );

        return $this->render(
            '@App/Default/product_block.html.twig',
            [
                'product' => $product,
            ]
        );
    }
```

and the `product_view.html.twig`
```
{% extends "::base.html.twig" %}

{% block body %}
    <div id="rightbtn"></div>
    <div id="leftbtn"></div>
    {{ jgp_ajax_block('AppBundle:Default:productAjax', {'item': product.slug, 'slug': product.group.slug}) }}
{% endblock %}

{% block custom_scripts %}
    <script>
	    $(document).on("click", ".product-selector", function () {
		    $.ajax({
			    url     : '{{ (path('product_ajax_request')) }}',
			    type    : "GET",
			    dataType: "json",
			    data    : {
				    "item": $(this).data("item"),
				    "slug": $(this).data("slug"),
			    },
			    async   : true,
			    success : function (data) {
				    $('[data-target="jgp-ajax-block"]').jgpAjaxBlock('reloadBlock');
			    },
		    });
		    return false;

	    });
    </script>
{% endblock %}
```

the `.product-selector` will be rendered with `jgp_ajax_block`

any idea?

**Comment by ghost** [comment]
Hi @AienTech,
I think that you're trying to use the bundle for something different from what it's supposed to do.

The idea of the bundle is to refresh a part of the page whose data may have changed as a result of another asynchronous request. Imagine you have a table with a list of users, and you have a button that opens a modal to create a new user asynchronously. After you have created the new user, the list would be outdated. In this case you would execute a block reload in the success callback of the user creation, so that the user list is refreshed to include the new user.

From your code I think you're trying to use the bundle to select the product to load in a block using ajax. This is not what the bundle is supposed to do, sorry.

**Comment by AienTech** [comment]
dear @jagilpe tnx for your response. I need to look for another bundle or even try to write my own for this purpose.

Thanks again
